<div class="homeTitleBox">
<a href="<?php echo $this->baseUrl(); ?>/videos/">LATEST BOOKMARK VIDEOS</a> &nbsp;
</div>
<div style="clear: both"> </div>
<br>

<?php// foreach($this->videos as $video): ?>
<?php foreach ($this->paginator as $video): ?>

	<div class="videoBoxElem" style="height: 160px">
			<div style="margin-bottom: 0px">
						</div>

			<div style="clear: both"></div>
			
			<div style="border:1px solid white; margin: 0 10px 10px 0; float: left">
				<div class="boxgrid captionfull">
					<A HREF="<?php echo $this->baseUrl(); ?>/videos/view/<?=$video["id"]?>/<?=$video["bandname"]?>">
						<img src="http://img.youtube.com/vi/<?=$video["tubecode"]?>/0.jpg" class="tubevideo">
					</a>
					<div class="cover boxcaption">
						<p><?=$video["songtitle"]?><br/></p>
					</div>
				</div>
			</div>

			<div style="margin: 0px; float: left; ">

				<A HREF="<?php echo $this->baseUrl(); ?>/videos/view/<?=$video["id"]?>/<?=$video["bandname"]?>">
					<? if($video["recom"]==1){ ?>
						<img src="<?php echo $this->baseUrl(); ?>/webroot/img/heart.png" width=10 border="0">
					<?}?>
					<span class="bandname"><?=$video["bandname"]?></span>
				</A><br /><br />
			</div>
			<div style="clear: both"></div>
		</div>

<?php endforeach; ?>

    <?php
	echo $this->paginator; 
	//print_r($this->paginator);
	?>
	<?php //echo $this->paginationControl($this->paginator, 'Elastic', 'controls.phtml'); ?>